var annotated_dup =
[
    [ "docstring", "namespacedocstring.html", [
      [ "PyClass", "classdocstring_1_1PyClass.html", "classdocstring_1_1PyClass" ]
    ] ],
    [ "pyexample", "namespacepyexample.html", [
      [ "PyClass", "classpyexample_1_1PyClass.html", "classpyexample_1_1PyClass" ]
    ] ],
    [ "A", "classA.html", "classA" ],
    [ "Adafruit_NeoPixel", "classAdafruit__NeoPixel.html", "classAdafruit__NeoPixel" ],
    [ "Adafruit_SH1106G", "classAdafruit__SH1106G.html", "classAdafruit__SH1106G" ],
    [ "Adafruit_SH1107", "classAdafruit__SH1107.html", "classAdafruit__SH1107" ],
    [ "Adafruit_SH110X", "classAdafruit__SH110X.html", "classAdafruit__SH110X" ],
    [ "Adafruit_SSD1306", "classAdafruit__SSD1306.html", "classAdafruit__SSD1306" ],
    [ "Afterdoc_Test", "classAfterdoc__Test.html", "classAfterdoc__Test" ],
    [ "Autolink_Test", "classAutolink__Test.html", "classAutolink__Test" ],
    [ "B", "classB.html", "classB" ],
    [ "BLESerial", "classBLESerial.html", "classBLESerial" ],
    [ "Button", "structButton.html", "structButton" ],
    [ "C", "classC.html", "classC" ],
    [ "C1", "classC1.html", null ],
    [ "C2", "classC2.html", null ],
    [ "C3", "classC3.html", null ],
    [ "C4", "classC4.html", null ],
    [ "C5", "classC5.html", null ],
    [ "Car", "structCar.html", "structCar" ],
    [ "CoordStruct", "structCoordStruct.html", "structCoordStruct" ],
    [ "D", "classD.html", "classD" ],
    [ "DelayState", "structDelayState.html", "structDelayState" ],
    [ "E", "classE.html", null ],
    [ "Encoder", "structEncoder.html", "structEncoder" ],
    [ "Enum_Test", "classEnum__Test.html", "classEnum__Test" ],
    [ "Example_Test", "classExample__Test.html", "classExample__Test" ],
    [ "Fn_Test", "classFn__Test.html", "classFn__Test" ],
    [ "Include_Test", "classInclude__Test.html", "classInclude__Test" ],
    [ "InputState", "structInputState.html", "structInputState" ],
    [ "Javadoc_Test", "classJavadoc__Test.html", "classJavadoc__Test" ],
    [ "Joystick", "structJoystick.html", "structJoystick" ],
    [ "Memgrp_Test", "classMemgrp__Test.html", "classMemgrp__Test" ],
    [ "mux_using_with", "classmux__using__with.html", "classmux__using__with" ],
    [ "Object", "structObject.html", null ],
    [ "Overload_Test", "classOverload__Test.html", "classOverload__Test" ],
    [ "Par_Test", "classPar__Test.html", null ],
    [ "QTstyle_Test", "classQTstyle__Test.html", "classQTstyle__Test" ],
    [ "RGBColor", "structRGBColor.html", "structRGBColor" ],
    [ "SomeNiceClass", "classSomeNiceClass.html", null ],
    [ "String", "classString.html", "classString" ],
    [ "Tag", "classTag.html", "classTag" ],
    [ "Test", "classTest.html", "classTest" ],
    [ "Test< T * >", "classTest_3_01T_01_5_01_4.html", "classTest_3_01T_01_5_01_4" ],
    [ "Test< void *, 200 >", "classTest_3_01void_01_5_00_01200_01_4.html", "classTest_3_01void_01_5_00_01200_01_4" ],
    [ "Truck", "structTruck.html", "structTruck" ],
    [ "UserSetting", "structUserSetting.html", "structUserSetting" ],
    [ "Vehicle", "structVehicle.html", "structVehicle" ]
];